### ISSUE TITLE
A few grammar things

### ISSUE THREAD

**Issue by duckwork** [iand675/haskell-checklist#1]
Does anything "algorithmic" or "data-structure-y" document it's big-O performance characteristics?
[the "it's" should be "its"]
Ensure that your functions are total
[needs a period at the end -- this applies to the last three checks of the first checklist]

I hope these suggestions are okay -- thanks for the checklist! It's quite useful.

**Comment by iand675** [comment]
Thanks @duckwork! I've fixed the issues you mentioned. Kind of embarrassing to switch its/it's. Must be an off day! :laughing:

**Comment by duckwork** [comment]
I know the feeling -- glad to help! -- Case
